# Generated by Django 4.1.4 on 2022-12-20 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='visited_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 14, 34, 7, 49383)),
        ),
    ]
